### ISSUE TITLE
[Security] User password can be grabbed via looking at the command-line arguments of EAC Launcher

### ISSUE THREAD

**Issue by veast-network** [ProjectMeowscles/Launcher#1]
![image](https://github.com/ProjectMeowscles/Launcher/assets/86145902/4bcf63a5-cf88-4288-8fde-67480f50c871)
ples fix

**Comment by LunarN0v4** [comment]
Could be fixed by using an SHA256 / SHA512 hash as the authentication password and implementing the same system for the backend.

**Comment by veast-network** [comment]
> Could be fixed by using an SHA256 / SHA512 hash as the authentication password and implementing the same system for the backend.

If you do this, I will throw bricks at your window

Here is my ideal system
![image](https://github.com/ProjectMeowscles/Launcher/assets/86145902/02417026-d8c7-4241-a12d-0dd9966a451b)
Thank you for coming to my presnetation

**Comment by plooshi** [comment]
epic has client_credentials auth method for a reason, and funnily enough, the client actually requests it presumably to do this work for you. so, if we just do that and supply it via the built-in -AUTH_TOKEN arg, this would be fixed

**Comment by LunarN0v4** [comment]
> > Could be fixed by using an SHA256 / SHA512 hash as the authentication password and implementing the same system for the backend.
> 
> If you do this, I will throw bricks at your window
> 
> Here is my ideal system ![image](https://private-user-images.githubusercontent.com/86145902/293114103-02417026-d8c7-4241-a12d-0dd9966a451b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MjI3OTgsIm5iZiI6MTcwMzcyMjQ5OCwicGF0aCI6Ii84NjE0NTkwMi8yOTMxMTQxMDMtMDI0MTcwMjYtZDhjNy00MjQxLWExMmQtMGRkOTk2NmE0NTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAwMTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTNmNWIzMjUzY2Y1OGIwMjQ4MDNlYWQ4OTIxOTAxMDIwM2Q4ZWU3YTQ3Mjk5OThiZTc0NGFmMDBkZDRiNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.paHRRnO56cGth3tcworcLnNeSiNAMTOiHoihwDJOPCg) Thank you for coming to my presnetation

it'll still use the plain password for that and therefore won't fix it

**Comment by plooshi** [comment]
patched by authorizing using exchange codes
